name: Simple CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: ${{ secrets.DB_NAME }}

    steps:
      # 1. Stáhne kód
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Nastaví Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Nainstaluje dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Spustí pipeline
      - name: Run pipeline
        run: python app/main.py